# Generated by Django 3.0.6 on 2020-05-18 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='the brand of the company', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='the main field of a product', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='enter the product name', max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('enable', models.BooleanField(default=True)),
                ('price', models.IntegerField(max_length=15)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almasroyan.Brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almasroyan.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique id for this product', primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almasroyan.Product')),
            ],
        ),
    ]
