# Generated by Django 3.0.6 on 2020-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almasroyan', '0002_auto_20200520_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_instance',
            name='Due_back',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
