# Generated by Django 3.0.6 on 2020-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almasroyan', '0003_product_instance_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_instance',
            name='Due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
