# Generated by Django 3.0.6 on 2020-05-26 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almasroyan', '0004_auto_20200520_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
